### ISSUE TITLE
Error: Cannot start service es7: OCI runtime create failed

### ISSUE THREAD

**Issue by msousa-fp** [rwynn/monstache-showcase#1]
Hi,

I'm having this issue when I run the import-showcase.sh

ERROR: for c-es  Cannot start service es7: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/d/celfocus/dds/monstache-showcase-master/elasticsearch/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/c5f0db3c0db47d2ac470046169dd37a9ae70e0cd633645da27bb686decf1101e/merged\\\" at \\\"/var/lib/docker/overlay2/c5f0db3c0db47d2ac470046169dd37a9ae70e0cd633645da27bb686decf1101e/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying Creating c-mongo ... done

ERROR: for es7  Cannot start service es7: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/mnt/d/celfocus/dds/monstache-showcase-master/elasticsearch/elasticsearch.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/c5f0db3c0db47d2ac470046169dd37a9ae70e0cd633645da27bb686decf1101e/merged\\\" at \\\"/var/lib/docker/overlay2/c5f0db3c0db47d2ac470046169dd37a9ae70e0cd633645da27bb686decf1101e/merged/usr/share/elasticsearch/config/elasticsearch.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected

Any help?

**Comment by rwynn** [comment]
I don’t remember ever seeing this error in docker. Maybe if you do a “docker volume ls” and delete the volumes associated with elasticsearch and retry?

**Comment by rwynn** [comment]
Maybe something from https://stackoverflow.com/questions/45972812/are-you-trying-to-mount-a-directory-onto-a-file-or-vice-versa would help. 

Are you using docker for windows?

**Comment by msousa-fp** [comment]
Yes I'm using docker for windows, but using ubuntu bash to run all of commands.

Maybe you could help me with what I'm trying to do...

I have a docker container running with elastic search 7 on port 9200
```
version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:7'
    ports:
      - '9200:9200'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
```

Have a docker container with mongodb
```version: '3.1'

networks:
  mons_mongo:

services:
  mongo_one:
    container_name: mongo1
    image: mongo
    command: mongod --replSet rs0
    ports:
      - 27017:27017
    networks:
      - mons_mongo
```

And I want to have a docker container with monstache
```
version: '3.1'

networks:
  mons_mongo:
  
services:
  monstache:
    container_name: monstache
    build: .
    restart: unless-stopped
    command: -f ./monstache-config.toml
    volumes:
      - ./monstache-config.toml:/go/src/cache-app/monstache-config.toml
    networks:
      - mons_mongo
```

Dockerfile
```
FROM rwynn/monstache:6.0.6
ADD ./monstache-config.toml /
RUN monstache -f monstache-config.toml
```
monstache-config.toml
```
## connection settings

## connect to MongoDB using the following URL
mongo-url = "mongodb://localhost:27017"

## connect to the Elasticsearch REST API at the following node URLs
elasticsearch-urls = ["http://localhost:9200"]

elasticsearch-max-conns = 10
replay = true
resume = true
resume-name = "default"
namespace-regex ='fulltext.^'
direct-read-namespaces = ["fulltext.articles"]
index-as-update = true
verbose = true
change-stream-namespaces = ["fulltext"]
```

If I run monstache directly from my windows machine `monstache -f .\monstache-config.toml`  it works fine

But if I `docker-compose up` I have an error 
```
Building monstache
Step 1/3 : FROM rwynn/monstache:6.0.6
 ---> aca4b7f4f630
Step 2/3 : ADD ./monstache-config.toml /
 ---> Using cache
 ---> 9b10727ade11
Step 3/3 : RUN monstache -f monstache-config.toml
 ---> Running in 2f97036bf3c4
ERROR 2019/06/11 15:45:29 Unable to connect to MongoDB using URL mongodb://localhost:27017: server selection error: server selection timeout
current topology: Type: Unknown
Servers:
Addr: localhost:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: dial tcp 127.0.0.1:27017: connect: connection refused
```
